/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import geometri3d.CincinBolaTorus;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class CincinBolaTorusFrame extends javax.swing.JFrame {

    /**
     * Creates new form CincinBolaDonutFrame
     */
    public CincinBolaTorusFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jariJariMinorTextField = new javax.swing.JTextField();
        jariJariMinorLabel = new javax.swing.JLabel();
        jariJariMajorLabel = new javax.swing.JLabel();
        jariJariMajorTextField = new javax.swing.JTextField();
        judulLabel = new javax.swing.JLabel();
        hitungButton = new javax.swing.JButton();
        volumeTextField = new javax.swing.JTextField();
        luasPermukaanTextField = new javax.swing.JTextField();
        volumeLabel = new javax.swing.JLabel();
        luasPermukaanLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jariJariMinorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jariJariMinorTextFieldActionPerformed(evt);
            }
        });

        jariJariMinorLabel.setText("Jari-jari Minor");

        jariJariMajorLabel.setText("Jari-jari Major");

        judulLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        judulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulLabel.setText("Cincin Bola (Torus)");

        hitungButton.setBackground(new java.awt.Color(51, 102, 255));
        hitungButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hitungButton.setForeground(new java.awt.Color(255, 255, 255));
        hitungButton.setText("Hitung");
        hitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungButtonActionPerformed(evt);
            }
        });

        volumeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        volumeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volumeLabel.setText("Volume");

        luasPermukaanLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        luasPermukaanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        luasPermukaanLabel.setText("Luas Permukaan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(hitungButton)
                    .addComponent(jariJariMajorTextField)
                    .addComponent(jariJariMajorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jariJariMinorTextField)
                    .addComponent(jariJariMinorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(judulLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(luasPermukaanTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(luasPermukaanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volumeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(volumeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(judulLabel)
                .addGap(18, 18, 18)
                .addComponent(jariJariMinorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jariJariMinorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jariJariMajorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jariJariMajorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hitungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luasPermukaanLabel)
                    .addComponent(volumeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luasPermukaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungButtonActionPerformed
        double jariJariMinorValue = Double.parseDouble(jariJariMinorTextField.getText());
        double jariJariMajorValue = Double.parseDouble(jariJariMajorTextField.getText());
        
        if (jariJariMinorValue <= 0 || jariJariMajorValue <= 0) {
            JOptionPane.showMessageDialog(
                null, 
                "Jari-jari Minor dan Major harus lebih besar dari 0.",
                "Warning",
                JOptionPane.WARNING_MESSAGE
            );
        } else if (jariJariMajorValue <= jariJariMinorValue) {
            JOptionPane.showMessageDialog(
                null, 
                "Untuk membentuk torus yang memiliki lubang di tengah maka Jari-jari Major harus lebih besar dari Jari-jari Minor.",
                "Warning",
                JOptionPane.WARNING_MESSAGE
            );
        } else {
            CincinBolaTorus cincinBolaTorus = new CincinBolaTorus(jariJariMinorValue, jariJariMajorValue);
            luasPermukaanTextField.setText(String.format("%.2f", cincinBolaTorus.hitungLuasPermukaan()));
            volumeTextField.setText(String.format("%.2f", cincinBolaTorus.hitungVolume()));
        }
    }//GEN-LAST:event_hitungButtonActionPerformed

    private void jariJariMinorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jariJariMinorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jariJariMinorTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CincinBolaTorusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CincinBolaTorusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CincinBolaTorusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CincinBolaTorusFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CincinBolaTorusFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hitungButton;
    private javax.swing.JLabel jariJariMajorLabel;
    private javax.swing.JTextField jariJariMajorTextField;
    private javax.swing.JLabel jariJariMinorLabel;
    private javax.swing.JTextField jariJariMinorTextField;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JLabel luasPermukaanLabel;
    private javax.swing.JTextField luasPermukaanTextField;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JTextField volumeTextField;
    // End of variables declaration//GEN-END:variables
}
