/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author asus
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lingkaranButton = new javax.swing.JButton();
        kerucutButton = new javax.swing.JButton();
        kerucutTerpancungButton = new javax.swing.JButton();
        tabungButton = new javax.swing.JButton();
        bolaButton = new javax.swing.JButton();
        juringBolaButton = new javax.swing.JButton();
        temberengBolaButton = new javax.swing.JButton();
        cincinBolaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lingkaranButton.setText("Lingkaran");

        kerucutButton.setText("Kerucut");

        kerucutTerpancungButton.setText("Kerucut Terpancung");

        tabungButton.setText("Tabung");

        bolaButton.setText("Bola");

        juringBolaButton.setText("Juring Bola");

        temberengBolaButton.setText("Tembereng Bola");

        cincinBolaButton.setText("Cincin Bola");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Geometri Lingkaran");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bolaButton)
                        .addGap(5, 5, 5)
                        .addComponent(juringBolaButton)
                        .addGap(4, 4, 4)
                        .addComponent(temberengBolaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cincinBolaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lingkaranButton)
                        .addGap(5, 5, 5)
                        .addComponent(kerucutTerpancungButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kerucutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabungButton))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lingkaranButton)
                    .addComponent(kerucutTerpancungButton)
                    .addComponent(tabungButton)
                    .addComponent(kerucutButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temberengBolaButton)
                    .addComponent(cincinBolaButton)
                    .addComponent(bolaButton)
                    .addComponent(juringBolaButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bolaButton;
    private javax.swing.JButton cincinBolaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton juringBolaButton;
    private javax.swing.JButton kerucutButton;
    private javax.swing.JButton kerucutTerpancungButton;
    private javax.swing.JButton lingkaranButton;
    private javax.swing.JButton tabungButton;
    private javax.swing.JButton temberengBolaButton;
    // End of variables declaration//GEN-END:variables
}
