/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uiold;
import geometri3d.KerucutTerpancung;
import java.awt.TextField;
import javax.swing.JOptionPane;

public class KerucutTerpancungFrame extends javax.swing.JFrame {

    /**
     * Creates new form CincinBolaDonutFrame
     */
    public KerucutTerpancungFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jariJariAtasTextField = new javax.swing.JTextField();
        jariJariBawahLabel = new javax.swing.JLabel();
        tinggiLabel = new javax.swing.JLabel();
        tinggiTextField = new javax.swing.JTextField();
        judullLabel = new javax.swing.JLabel();
        hitungButton = new javax.swing.JButton();
        volumeTextField = new javax.swing.JTextField();
        luasPermukaanTextField = new javax.swing.JTextField();
        volumeLabel = new javax.swing.JLabel();
        luasPermukaanLabel = new javax.swing.JLabel();
        jariJariAtasLabel = new javax.swing.JLabel();
        jariJariBawahTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jariJariAtasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jariJariAtasTextFieldActionPerformed(evt);
            }
        });

        jariJariBawahLabel.setText("Jari-jari Bawah");

        tinggiLabel.setText("Tinggi Kerucut Terpancung");

        judullLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        judullLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judullLabel.setText("Kerucut Terpancung");

        hitungButton.setBackground(new java.awt.Color(51, 102, 255));
        hitungButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hitungButton.setForeground(new java.awt.Color(255, 255, 255));
        hitungButton.setText("Hitung");
        hitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungButtonActionPerformed(evt);
            }
        });

        volumeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeTextFieldActionPerformed(evt);
            }
        });

        volumeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        volumeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volumeLabel.setText("Volume");

        luasPermukaanLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        luasPermukaanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        luasPermukaanLabel.setText("Luas Permukaan");

        jariJariAtasLabel.setText("Jari-jari Atas");

        jariJariBawahTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jariJariBawahTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(luasPermukaanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(luasPermukaanTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(volumeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(volumeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jariJariBawahLabel, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(judullLabel, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tinggiTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tinggiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jariJariAtasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jariJariAtasTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jariJariBawahTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(hitungButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(judullLabel)
                .addGap(18, 18, 18)
                .addComponent(jariJariBawahLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jariJariBawahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jariJariAtasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jariJariAtasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tinggiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tinggiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hitungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luasPermukaanLabel)
                    .addComponent(volumeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luasPermukaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungButtonActionPerformed
        try {
            double jariJariBawahValue = Double.parseDouble(jariJariBawahTextField.getText()); 
            double jariJariAtasValue = Double.parseDouble(jariJariAtasTextField.getText());
            double tinggiValue = Double.parseDouble(tinggiTextField.getText());

            if (jariJariBawahValue <= 0 || jariJariAtasValue <= 0 || tinggiValue <= 0) {
                JOptionPane.showMessageDialog(this, "Semua nilai harus lebih besar dari 0!", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (jariJariBawahValue <= jariJariAtasValue) {
                JOptionPane.showMessageDialog(this, "Jari-jari bawah harus lebih besar dari jari-jari atas!", "Logika Salah", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            geometri3d.KerucutTerpancung kt = new geometri3d.KerucutTerpancung(jariJariBawahValue, tinggiValue, jariJariAtasValue);

            luasPermukaanTextField.setText(String.format("%.2f", kt.hitungLuasPermukaan()));
            volumeTextField.setText(String.format("%.2f", kt.hitungVolume()));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukin angka yang bener dong, King!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_hitungButtonActionPerformed

    private void jariJariAtasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jariJariAtasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jariJariAtasTextFieldActionPerformed

    private void jariJariBawahTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jariJariBawahTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jariJariBawahTextFieldActionPerformed

    private void volumeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volumeTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KerucutTerpancung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KerucutTerpancung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KerucutTerpancung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KerucutTerpancung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KerucutTerpancungFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hitungButton;
    private javax.swing.JLabel jariJariAtasLabel;
    private javax.swing.JTextField jariJariAtasTextField;
    private javax.swing.JLabel jariJariBawahLabel;
    private javax.swing.JTextField jariJariBawahTextField;
    private javax.swing.JLabel judullLabel;
    private javax.swing.JLabel luasPermukaanLabel;
    private javax.swing.JTextField luasPermukaanTextField;
    private javax.swing.JLabel tinggiLabel;
    private javax.swing.JTextField tinggiTextField;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JTextField volumeTextField;
    // End of variables declaration//GEN-END:variables
}
